name: 'check run auto'
description: 'check run auto create, update and complete action'
author: 'MeilCli'
branding:
  icon: check
  color: purple
runs:
  using: 'node12'
  pre: 'dist/pre/index.js'
  main: 'dist/main/index.js'
  post: 'dist/post/index.js'
